### ISSUE TITLE
Binary-only pieces of software

### ISSUE THREAD

**Issue by lucafavatella** [TeamWin/android_device_motorola_cedric#1]
Could you please clarify how the binary-only pieces of software in branch `android-7.1` (726c512dfb7e39c5e19339e86cdb4eb6dc1fa3a7) were obtained, so that they can be verified or - better - rebuilt. I list them below:
```
/dt.img
/kernel
/recovery/root/sbin/qseecomd
/recovery/root/vendor/lib/libQSEEComAPI.so
/recovery/root/vendor/lib/libSecureUILib.so
/recovery/root/vendor/lib/libStDrvInt.so
/recovery/root/vendor/lib/libdiag.so
/recovery/root/vendor/lib/libdrmfs.so
/recovery/root/vendor/lib/libdrmtime.so
/recovery/root/vendor/lib/librpmb.so
/recovery/root/vendor/lib/libsecureui_svcsock.so
/recovery/root/vendor/lib/libssd.so
/recovery/root/vendor/lib/libtime_genoff.so
/recovery/root/vendor/lib/hw/keystore.msm8937.so
```

**Comment by lucafavatella** [comment]
`dt.img` and `kernel` [appear to be buildable from source](https://github.com/Sohamlad7/android_device_motorola_cedric/commit/cb19d25f470cf5de7eddd2fc370c4fc6ca0337e2).

**Comment by nift4** [comment]
The other binaries are from the stock ROM
Available also here: https://github.com/Sohamlad7/android_vendor_motorola_cedric

**Comment by nift4** [comment]
> `dt.img` and `kernel` [appear to be buildable from source](https://github.com/Sohamlad7/android_device_motorola_cedric/commit/cb19d25f470cf5de7eddd2fc370c4fc6ca0337e2).

The source used is: https://github.com/Sohamlad7/android_kernel_motorola_msm8937/tree/twrp-treble
